################################################################################################################
# Use this file to build from local source. Note you have to 'docker system prune -a' on code changes or 'docker-compose build'
# Sample docker-compose file that will allow for connecting ES and HQ between separate containers
# Note that the container_name (elasticsearch) is used as a default connection url in the HQ settings.
# For pushing from local: https://ropenscilabs.github.io/r-docker-tutorial/04-Dockerhub.html
################################################################################################################

version: '3'
services:
  elastichq:
    build:
      context: ../
      dockerfile: Dockerfile
    #image: elastichq:4.0.0
    container_name: elastichq
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
      - HQ_DEBUG=True
    ports:
      - 5000:5000
    networks:
      - esnet

  elasticsearch:
    image: elasticsearch:8.11.3

    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - node.name=node_1
      - network.host=0.0.0.0
      - network.publish_host=0.0.0.0
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - action.destructive_requires_name=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
networks:
  esnet:
    driver: bridge